### ISSUE TITLE
Translation tool

### ISSUE THREAD

**Issue by jugendhacker** [Johann150/multilang#4]
I tried to make a simple tool for translating! But it does not work at the moment. Just for taking a look: jugendhacker/multilang@b2bc740

**Comment by Johann150** [comment]
Maybe you could also take the newly added chunk translations into account.
But it would already be very nice to have a tool to create the file structure for alias translation. 👍

**Comment by Johann150** [comment]
I have created `translator/chunks.html` as a skelleton for the chunk translation.  
The file `translator/chunk-api.md` contains some info on how to use the new API for chunk translation. Maybe you could have a look into it.

**Comment by Johann150** [comment]
The chunk translation is done except that there is **no way of adding a new chunk** from the translator tool.

**Comment by jugendhacker** [comment]
ok nice

**Comment by jugendhacker** [comment]
Is there something left to do on the translator or can I close this issue?
